<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Autorus\CarService\Grpc\CarBrandListResponse\CarBrandItem instead.
     * @deprecated
     */
    class CarBrandListResponse_CarBrandItem {}
}
class_exists(CarBrandListResponse\CarBrandItem::class);
@trigger_error('Autorus\CarService\Grpc\CarBrandListResponse_CarBrandItem is deprecated and will be removed in the next major release. Use Autorus\CarService\Grpc\CarBrandListResponse\CarBrandItem instead', E_USER_DEPRECATED);

