<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Autorus\CarService\Grpc\CarClassReadResponse\Data instead.
     * @deprecated
     */
    class CarClassReadResponse_Data {}
}
class_exists(CarClassReadResponse\Data::class);
@trigger_error('Autorus\CarService\Grpc\CarClassReadResponse_Data is deprecated and will be removed in the next major release. Use Autorus\CarService\Grpc\CarClassReadResponse\Data instead', E_USER_DEPRECATED);

