<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Autorus\CarService\Grpc\CarClassListResponse\CarClassItem instead.
     * @deprecated
     */
    class CarClassListResponse_CarClassItem {}
}
class_exists(CarClassListResponse\CarClassItem::class);
@trigger_error('Autorus\CarService\Grpc\CarClassListResponse_CarClassItem is deprecated and will be removed in the next major release. Use Autorus\CarService\Grpc\CarClassListResponse\CarClassItem instead', E_USER_DEPRECATED);

