<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Autorus\CarService\Grpc\CarClassListResponse\Data instead.
     * @deprecated
     */
    class CarClassListResponse_Data {}
}
class_exists(CarClassListResponse\Data::class);
@trigger_error('Autorus\CarService\Grpc\CarClassListResponse_Data is deprecated and will be removed in the next major release. Use Autorus\CarService\Grpc\CarClassListResponse\Data instead', E_USER_DEPRECATED);

