<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Autorus\CarService\Grpc\CarModelListResponse\CarModelItem instead.
     * @deprecated
     */
    class CarModelListResponse_CarModelItem {}
}
class_exists(CarModelListResponse\CarModelItem::class);
@trigger_error('Autorus\CarService\Grpc\CarModelListResponse_CarModelItem is deprecated and will be removed in the next major release. Use Autorus\CarService\Grpc\CarModelListResponse\CarModelItem instead', E_USER_DEPRECATED);

