<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Autorus\CarService\Grpc\CarModelListResponse\Data instead.
     * @deprecated
     */
    class CarModelListResponse_Data {}
}
class_exists(CarModelListResponse\Data::class);
@trigger_error('Autorus\CarService\Grpc\CarModelListResponse_Data is deprecated and will be removed in the next major release. Use Autorus\CarService\Grpc\CarModelListResponse\Data instead', E_USER_DEPRECATED);

