<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

use Spiral\GRPC;

interface CarServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "CarService.CarService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarBrandCreateRequest $in
    * @return CarBrandCreateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarBrandCreate(GRPC\ContextInterface $ctx, CarBrandCreateRequest $in): CarBrandCreateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarBrandReadRequest $in
    * @return CarBrandReadResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarBrandRead(GRPC\ContextInterface $ctx, CarBrandReadRequest $in): CarBrandReadResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarBrandUpdateRequest $in
    * @return CarBrandUpdateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarBrandUpdate(GRPC\ContextInterface $ctx, CarBrandUpdateRequest $in): CarBrandUpdateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarBrandDeleteRequest $in
    * @return CarBrandDeleteResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarBrandDelete(GRPC\ContextInterface $ctx, CarBrandDeleteRequest $in): CarBrandDeleteResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarBrandListRequest $in
    * @return CarBrandListResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarBrandList(GRPC\ContextInterface $ctx, CarBrandListRequest $in): CarBrandListResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarClassCreateRequest $in
    * @return CarClassCreateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarClassCreate(GRPC\ContextInterface $ctx, CarClassCreateRequest $in): CarClassCreateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarClassReadRequest $in
    * @return CarClassReadResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarClassRead(GRPC\ContextInterface $ctx, CarClassReadRequest $in): CarClassReadResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarClassUpdateRequest $in
    * @return CarClassUpdateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarClassUpdate(GRPC\ContextInterface $ctx, CarClassUpdateRequest $in): CarClassUpdateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarClassDeleteRequest $in
    * @return CarClassDeleteResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarClassDelete(GRPC\ContextInterface $ctx, CarClassDeleteRequest $in): CarClassDeleteResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarClassListRequest $in
    * @return CarClassListResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarClassList(GRPC\ContextInterface $ctx, CarClassListRequest $in): CarClassListResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarModelCreateRequest $in
    * @return CarModelCreateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarModelCreate(GRPC\ContextInterface $ctx, CarModelCreateRequest $in): CarModelCreateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarModelReadRequest $in
    * @return CarModelReadResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarModelRead(GRPC\ContextInterface $ctx, CarModelReadRequest $in): CarModelReadResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarModelUpdateRequest $in
    * @return CarModelUpdateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarModelUpdate(GRPC\ContextInterface $ctx, CarModelUpdateRequest $in): CarModelUpdateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarModelDeleteRequest $in
    * @return CarModelDeleteResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarModelDelete(GRPC\ContextInterface $ctx, CarModelDeleteRequest $in): CarModelDeleteResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CarModelListRequest $in
    * @return CarModelListResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CarModelList(GRPC\ContextInterface $ctx, CarModelListRequest $in): CarModelListResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkCreateRequest $in
    * @return WorkCreateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkCreate(GRPC\ContextInterface $ctx, WorkCreateRequest $in): WorkCreateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkReadRequest $in
    * @return WorkReadResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkRead(GRPC\ContextInterface $ctx, WorkReadRequest $in): WorkReadResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkUpdateRequest $in
    * @return WorkUpdateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkUpdate(GRPC\ContextInterface $ctx, WorkUpdateRequest $in): WorkUpdateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkDeleteRequest $in
    * @return WorkDeleteResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkDelete(GRPC\ContextInterface $ctx, WorkDeleteRequest $in): WorkDeleteResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkListRequest $in
    * @return WorkListResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkList(GRPC\ContextInterface $ctx, WorkListRequest $in): WorkListResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkGroupCreateRequest $in
    * @return WorkGroupCreateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkGroupCreate(GRPC\ContextInterface $ctx, WorkGroupCreateRequest $in): WorkGroupCreateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkGroupReadRequest $in
    * @return WorkGroupReadResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkGroupRead(GRPC\ContextInterface $ctx, WorkGroupReadRequest $in): WorkGroupReadResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkGroupUpdateRequest $in
    * @return WorkGroupUpdateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkGroupUpdate(GRPC\ContextInterface $ctx, WorkGroupUpdateRequest $in): WorkGroupUpdateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkGroupDeleteRequest $in
    * @return WorkGroupDeleteResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkGroupDelete(GRPC\ContextInterface $ctx, WorkGroupDeleteRequest $in): WorkGroupDeleteResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param WorkGroupListRequest $in
    * @return WorkGroupListResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function WorkGroupList(GRPC\ContextInterface $ctx, WorkGroupListRequest $in): WorkGroupListResponse;
}
