<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Autorus\CarService\Grpc\WorkGroupListResponse\WorkGroupItem instead.
     * @deprecated
     */
    class WorkGroupListResponse_WorkGroupItem {}
}
class_exists(WorkGroupListResponse\WorkGroupItem::class);
@trigger_error('Autorus\CarService\Grpc\WorkGroupListResponse_WorkGroupItem is deprecated and will be removed in the next major release. Use Autorus\CarService\Grpc\WorkGroupListResponse\WorkGroupItem instead', E_USER_DEPRECATED);

