<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Autorus\CarService\Grpc\WorkListResponse\WorkItem instead.
     * @deprecated
     */
    class WorkListResponse_WorkItem {}
}
class_exists(WorkListResponse\WorkItem::class);
@trigger_error('Autorus\CarService\Grpc\WorkListResponse_WorkItem is deprecated and will be removed in the next major release. Use Autorus\CarService\Grpc\WorkListResponse\WorkItem instead', E_USER_DEPRECATED);

