<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Autorus\CarService\Grpc\CarModelReadResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CarService.CarModelReadResponse.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     */
    private $uuid = '';
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>string car_brand = 3;</code>
     */
    private $car_brand = '';
    /**
     * Generated from protobuf field <code>string car_class = 4;</code>
     */
    private $car_class = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uuid
     *     @type string $title
     *     @type string $car_brand
     *     @type string $car_class
     * }
     */
    public function __construct($data = NULL) {
        \Autorus\CarService\Grpc\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string car_brand = 3;</code>
     * @return string
     */
    public function getCarBrand()
    {
        return $this->car_brand;
    }

    /**
     * Generated from protobuf field <code>string car_brand = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCarBrand($var)
    {
        GPBUtil::checkString($var, True);
        $this->car_brand = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string car_class = 4;</code>
     * @return string
     */
    public function getCarClass()
    {
        return $this->car_class;
    }

    /**
     * Generated from protobuf field <code>string car_class = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCarClass($var)
    {
        GPBUtil::checkString($var, True);
        $this->car_class = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Data::class, \Autorus\CarService\Grpc\CarModelReadResponse_Data::class);

